'use strict';

exports.waitlistedStudentsData =
  "select a.person_id as \"person_id\","
      + " a.year_term as \"year_term\","
      + " a.curriculum_id as \"curriculum_id\","
      + " a.title_code as \"title_code\","
      + " a.section_number as \"section_number\","
      + " b.byu_id as \"byu_id\","
      + " b.sort_name as \"student_name\","
      + " to_char(a.date_requested, 'dd Mon yyyy hh24:mi:ss') as \"date_time_requested\","
      + " a.sequencer as \"sequencer\","
      + " rpad(a.dept_name, 6)||a.catalog_number||a.catalog_suffix as \"course_name\","
      + " a.credit_hours as \"credit_hours\","
      + " a.size_mix_category as \"size_mix_category\","
      + " a.added_by_id as \"added_by_id\","
      + " c.sort_name as \"added_by_name\","
      + " a.add_error_message as \"add_error_message\","
      + " to_char(a.error_timestamp, 'dd Mon yyyy hh24:mi:ss') as \"date_time_of_error\""
 + " from waitlist a,"
      + " person b,"
      + " person c"
+ " where a.year_term = :1"
  + " and a.curriculum_id = :2"
  + " and a.title_code = :3"
  + " and a.section_number = :4"
  + " and b.person_id = a.person_id"
  + " and c.person_id = a.added_by_id"
+ " order by b.sort_name";

