'use strict';

exports.assignedSchedulesData =
  "select a.event_type as \"schedule_type\","
      + " a.event_id as \"schedule_id\","
      + " a.sequence_number as \"sequence_number\","
      + " substr(a.event_id, 16, 5) as \"year_term\","
      + " substr(a.event_id, 21, 5) as \"curriculum_id\","
      + " substr(a.event_id, 26, 3) as \"title_code\","
      + " substr(a.event_id, 29, 3) as \"section_number\","
      + " a.institution as \"institution\","
      + " a.building as \"building\","
      + " a.room as \"room\","
      + " nvl(a.mon||a.tue||a.wed||decode(nvl(a.thu, ''), 'R', 'Th', '')||a.fri||a.sat||a.sun, 'TBA') as \"days_taught\","
      + " a.mon as \"mon\","
      + " a.tue as \"tue\","
      + " a.wed as \"wed\","
      + " a.thu as \"thu\","
      + " a.fri as \"fri\","
      + " a.sat as \"sat\","
      + " a.sat as \"sun\","
      + " nvl(to_char(a.use_start_date, 'dd Mon yyyy'), 'TBA') as \"use_start_date\","
      + " nvl(to_char(a.use_end_date, 'dd Mon yyyy'), 'TBA') as \"use_end_date\","
      + " nvl(to_char(to_date(a.begin_time, 'hh24mi'), 'hh:mi pm'), 'TBA')||'-'||nvl(to_char(to_date(a.end_time, 'hh24mi'), 'hh:mi pm'), 'TBA') as \"time_taught\","
      + " nvl(a.begin_time, 'TBA') as \"begin_time\","
      + " nvl(a.end_time, 'TBA') as \"end_time\","
      + " nvl(a.status, '') as \"status\","
      + " nvl(a.set_up_id, '') as \"set_up_id\","
      + " nvl(a.set_up_description, '') as \"set_up_description\","
      + " nvl(a.event_reason, '') as \"schedule_reason\","
      + " nvl(a.updated_by_id, '') as \"updated_by_id\","
      + " nvl(b.sort_name, '') as \"updated_by_name\","
      + " nvl(a.allow_conflict, 'N') as \"allow_conflict\""
 + " from event_schedule a,"
      + " person b"
+ " where a.event_type IN ('CLS', 'FINAL EXAM')"
  + " and a.event_id = 'BYU PROVO      ' || :1 || :2 || :3 || :4"
  + " and b.person_id (+) = a.updated_by_id"
+ " order by a.event_type, a.sequence_number";

