'use strict';

exports.addApprovedStudentsData =
  "select a.credit_institution as \"credit_institution\","
      + " a.year_term as \"year_term\","
      + " a.curriculum_id as \"curriculum_id\","
      + " a.title_code as \"title_code\","
      + " a.section_number as \"section_number\","
      + " rpad(b.dept_name, 6)||b.catalog_number||b.catalog_suffix as \"course_name\","
      + " a.person_id as \"student_id\","
      + " c.sort_name as \"student_name\","
      + " to_char(a.created_date_time, 'dd Mon yyyy hh24:mi:ss') as \"date_time_created\","
      + " nvl(a.created_by_id, '') as \"created_by_id\","
      + " d.sort_name as \"created_by_name\","
      + " nvl(to_char(a.redeemed_date_time, 'dd Mon yyyy hh24:mi:ss'), '') as \"date_time_redeemed\","
      + " nvl(a.audit_flag, '') as \"audit_flag\""
 + " from class_section_add_permission a,"
      + " course_title b,"
      + " person c,"
      + " person d"
+ " where a.year_term = :1"
  + " and a.curriculum_id = :2"
  + " and a.title_code = :3"
  + " and a.section_number = :4"
  + " and b.curriculum_id = a.curriculum_id"
  + " and b.title_code = a.title_code"
  + " and c.person_id (+) = a.person_id"
  + " and d.person_id (+) = a.created_by_id"
+ " order by c.sort_name";

