'use strict';

exports.basicData =
  "select a.year_term as \"year_term\","
      + " a.curriculum_id as \"curriculum_id\","
      + " a.title_code as \"title_code\","
      + " a.section_number as \"section_number\","
      + " a.credit_institution as \"credit_institution\","
      + " nvl(a.dept_name, 'xxxxx') as \"subject_area\","
      + " nvl(a.catalog_number, '000') as \"course_number\","
      + " nvl(a.catalog_suffix, '') as \"course_suffix\","
      + " nvl(a.section_type, 'unknown') as \"section_type\","
      + " nvl(a.credit_type, 'S') as \"block_code\","
      + " nvl(a.section_status_flag, 'N') as \"class_status\","
      + " nvl(a.reg_method, 'O') as \"reg_method\","
      + " nvl(a.lab_quiz_section, 'N') as \"lab_quiz_flag\","
      + " nvl(a.fee, '') as \"fee\","
      + " nvl(a.honors, 'N') as \"honors\","
      + " nvl(a.service_learning, 'N') as \"service_learning\","
      + " nvl(a.fixed_or_variable, 'F') as \"fixed_or_variable\","
      + " nvl(a.credit_hours, 0.0) as \"credit_hours\","
      + " nvl(a.minimum_credit_hours, 0.0) as \"minimum_credit_hours\","
      + " nvl(a.section_size, 0) as \"class_size\","
      + " nvl(a.total_enrolled, 0) as \"total_enrolled\","
      + " nvl(to_char(a.start_date, 'dd Mon yyyy'), '') as \"class_start_date\","
      + " nvl(to_char(a.end_date, 'dd Mon yyyy'), '') as \"class_end_date\","
      + " nvl(to_char(a.reg_start_date, 'dd Mon yyyy'), '') as \"reg_start_date\","
      + " nvl(to_char(a.reg_end_date, 'dd Mon yyyy'), '') as \"reg_end_date\","
      + " nvl(to_char(a.wdrop_date, 'dd Mon yyyy'), '') as \"withdraw_deadline_date\","
      + " nvl(to_char(a.control_mix_date, 'dd Mon yyyy'), '') as \"control_mix_date\","
      + " nvl(a.waitlist_status, 'D') as \"waitlist_status\","
      + " nvl(a.combine_rolls, 'N') as \"combine_linked_rolls\","
      + " nvl(a.combine_counts, 'N') as \"combine_linked_counts\","
      + " nvl(a.combine_yyt, '') as \"link_to_year_term\","
      + " nvl(a.combine_curr_id, '') as \"link_to_curriculum_id\","
      + " nvl(a.combine_title_code, '') as \"link_to_title_code\","
      + " nvl(a.combine_section, '') as \"link_to_section_number\","
      + " b.transcript_title as \"course_title\""
 + " from class_section a,"
      + " course_title b"
+ " where a.year_term = :1"
  + " and a.curriculum_id = :2"
  + " and a.title_code = :3"
  + " and a.section_number = :4"
  + " and b.curriculum_id = a.curriculum_id"
  + " and b.title_code = a.title_code";

